### ISSUE TITLE
colab?

### ISSUE THREAD

**Issue by osushilover** [swz30/Restormer#10]
I am pleased with your work; the level of completeness is really professional!
Do you guys have any plan to release the code for Google Colab?
Unfortunately, I can't run the code on my local machine due to some poor factors.

**Comment by fdsig** [comment]
Hey @osushilover,

A great question! 
I have made a Colab notebook which is available: 

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1R_RHff93lEPE6aLTkQYI5Ni2Qo5-832M?usp=sharing)

Really hope this helps!

Frida

**Comment by osushilover** [comment]
@fdsig YOUR JOB is great!
But so sorry...
Though this notebook is running, I don't know how to try my own image files.
What can I do next?

**Comment by fdsig** [comment]
in order to obtain metrics, you will need images that have degradation/original this is what metrics such as ssim (structural similarity index)  compute. Perhaps replace the original and degraded images in the appropriate directories (structure outlined repository README.md) 
Here are other image restoration datasets:  [<img src="https://paperswithcode.com/static/logo.png" width="30" height="30">](https://paperswithcode.com/sota/image-denoising-on-ffhq)

**Comment by nishantb06** [comment]
Do we need Ground truth images for just inferencing ? Also how should i proceed with de-noisinng my own png image. I can see that it is only compatible with .mat files
