### ISSUE TITLE
Does not correspond to paper MPRNet

### ISSUE THREAD

**Issue by Jeasco** [swz30/Restormer#8]
![0V%7W6C)GL~C%I5K10NZ%AM](https://user-images.githubusercontent.com/57336850/143376490-89d36cbf-6ecd-434b-8606-2d6f72044bdb.png)

Figure 3 in this paper and Figure 5 in the author's previous paper MPRNet use the same test picture, the SAME PSNR, but the visualization results are very different. Whether I can doubt the authenticity and rigor of the results of the paper

**Comment by swz30** [comment]
Hi @Jeasco,

We used the publicly available models released on MPRNet Github repository (https://github.com/swz30/MPRNet) for comparison with Restormer. The image quality scores and visualizations can be verified with the publicly available models and codes. Differences in specific visualization could be due to earlier trained versions of MPRNet before its submission. Further, you can check our numerous examples available in the newly uploaded supplementary [pdf](https://drive.google.com/file/d/13AgJJEjYRNrUuMWkiRWPo_19F6xCzgIV/view?usp=sharing) where Restormer obtains significant improvements over MPRNet.

**Comment by CR7forMadrid** [comment]
6
